<?xml version="1.0"?>
<package format="3">
  <name>hive_bt_server</name>
  <version>0.1.0</version>
  <description>Hive BT router/dispatcher</description>

  <maintainer email="you@example.com">You</maintainer>
  <license>MIT</license>

  <!-- build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- dependencies -->
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>hive_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
